#!/usr/bin/env node

import { template, extended } from './micro-template.js';

export function serializeTemplates(target, options = {}) {
	template.get = id => target[id].source;
	template.cache.clear();

	const timestamp = new Date().toISOString();
	let serialized = `/**
 * Auto-generated by micro-template-serialize
 * Generated at: ${timestamp}
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file contains pre-compiled templates from micro-template.js
 * Source: https://github.com/cho45/micro-template.js
 */

const compiled = {};
`;

	const { onProgress } = options;
	const entries = Object.entries(target);
	
	for (let i = 0; i < entries.length; i++) {
		const [id, entry] = entries[i];
		const keys = entry.keys || [];
		
		if (onProgress) {
			onProgress({ 
				current: i + 1, 
				total: entries.length, 
				templateId: id,
				keys: keys.length 
			});
		}
		
		const func = extended(id, keys);
		const compiled = func.compiled;
		serialized += `compiled['${id}'] = ` + compiled.toString().replace(/\/\/#.*/g, '') + ';\n';
		serialized += `compiled['${id}'].keys = ` + JSON.stringify(func.keys) + ';\n';
	}

	serialized += `const regexp = /[<>"'&]/;\n`;
	serialized += `const escapeHTML = ` + template.escapeHTML.toString() + ';\n';

	serialized += `const template = ` + (function (id, stash) {
		const me = template;
		const func = compiled[id];
		if (!func) {
			throw new Error(`Template "${id}" not found.`);
		}
		return func.call(null, me.context = { escapeHTML, line: 1, ret: '', stash }, ...func.keys.map(key => stash[key]));
	}).toString() + ';\n';

	serialized += `const extended = ` + extended.toString() + ';\n';

	serialized += `export { template, extended };\n`;

	return serialized;
}
